name: Linters and Test

on:
  pull_request:
    branches:
      - master
      - develop
    types: [opened, edited, reopened, synchronize]
jobs:
  install-node-modules:
    name: Install Node Modules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'
          cache: npm
      - name: Install packages
        run: npm i
        env:
          # And add the additional registry token here:
          # FORTAWESOME_TOKEN: ${{secrets.FORTAWESOME_TOKEN}}
          NODE_AUTH_TOKEN: ${{ secrets.TOKEN_REG }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Execute lint JS
        run: npm run lint
